name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        uses: ./.github/workflows/Build.yml

    release:
        needs: build
        uses: ./.github/workflows/Release.yml
        with:
            ci_check: true

    lint:
        uses: J-Afzal/Linters/.github/workflows/Linting.yml@main
        with:
            path_to_linters_submodule_root: ./submodules/Linters
            run_powershell_linters: true
            run_cpp_linters: true
