name: Continuous Deployment

run-name: CD - ${{ github.run_number }} - ${{ github.ref }}

on:
    push:
        branches:
            - main

jobs:
    build:
        uses: ./.github/workflows/Build.yml

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
            id-token: write
        defaults:
            run:
                shell: pwsh

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download built executable artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: terminal-games-*

            - name: Create new release
              run: |
                  $currentDate = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
                  gh release create "terminal-games-$currentDate" ./terminal-games-macos-latest/terminal-games-macos-latest ./terminal-games-ubuntu-latest/terminal-games-ubuntu-latest ./terminal-games-windows-latest/terminal-games-windows-latest.exe --generate-notes --latest --title "Terminal Games $currentDate"
              env:
                  GH_TOKEN: ${{ github.token }}

            - name: Upload doxygen documentation artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  name: doxygen-docs
                  path: ./docs/html/

            - name: Release GitHub pages
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: doxygen-docs
                  token: ${{ github.token }}
