name: Continuous Deployment

run-name: CD - ${{ github.run_number }} - ${{ github.ref }}

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        uses: ./.github/workflows/Build.yml

    release:
        uses: ./.github/workflows/Release.yml
        needs: build
