name: Performance Tests

run-name: Performance Tests - ${{ github.run_number }} - ${{ github.head_ref }}

# on: workflow_dispatch # TODO: for testing
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        uses: ./.github/workflows/Build.yml

    performance_tests:
        needs: build
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest
        defaults:
            run:
                shell: pwsh

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Download performance test build
              uses: actions/download-artifact@v4
              with:
                  pattern: lane-and-object-detection-performance-tests-${{ matrix.os }}

            - name: Run performance tests
              run: |
                  curl -o .\resources\yolo\yolov7.weights "https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov7.weights"

                  ./lane-and-object-detection-performance-tests-${{ matrix.os }}/lane-and-object-detection-performance-tests `
                      -p ${{ matrix.os }} `
                      -d sqlite-${{ matrix.os }}.db `
                      -i ./tests/performance_tests/benchmark.mp4 `
                      -y ./resources/yolo/ `
                      -r 1;

            - name: Upload sqlite database
              uses: actions/upload-artifact@v4
              with:
                  name: sqlite-${{ matrix.os }}
                  path: ./sqlite-${{ matrix.os }}.db
                  if-no-files-found: error

    performance_graphs:
        needs: performance_tests

        runs-on: ubuntu-latest

        defaults:
            run:
                shell: pwsh

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Download sqlite databases
              uses: actions/download-artifact@v4
              with:
                  pattern: sqlite-*

            - name: Run performance tests
              run: |
                  pip install -r ./requirements.txt

                  python -m ./tests/main.py `
                      -d ./sqlite-macos-latest/sqlite-macos-latest.db,./sqlite-ubuntu-latest/sqlite-ubuntu-latest.db,./sqlite-windows-latest/sqlite-windows-latest.db `
                      -o ./tests/performance_graphs/output/

            - name: Upload performance graphs
              uses: actions/upload-artifact@v4
              with:
                  name: performance-graphs
                  path: ./tests/performance_graphs/output/
                  if-no-files-found: error
